 spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/golfapp
    username: pronane
    password: password
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    properties:
     hibernate:
      dialect: org.hibernate.dialect.MariaDB103Dialect